services:
    postgres_db:
        image: bitnami/postgresql:16.2.0
        ports:
            - 5432:5432
        environment:
            - POSTGRESQL_USERNAME=docker
            - POSTGRESQL_PASSWORD=docker
        volumes:
            - postgresql_data:/bitnami/postgresql
        networks:
            - ftask-management_net

    redis_cache:
        image: bitnami/redis:7.0.15
        ports:
            - 6379:6379
        environment:
            - REDIS_PASSWORD=docker
        volumes:
            - redis_cache:/bitnami/redis/data
        networks:
            - ftask-management_net

volumes:
    postgresql_data:
        driver: local
    redis_cache:
        driver: local

networks:
    ftask-management_net:
